name: COBOL Check Automation
on:
  push:
    branches: [main]
jobs:
    cobol-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Or a specific Node.js version compatible with Zowe CLI

      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@zowe-v2-lts

      - name: Run Zowe CLI commands (and potentially Java-dependent tasks)
        run: |
          zowe --version          
          # Add commands that might interact with Java-based Zowe components here
          
      - name: Running cobol check 
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: 
          # Here we'll add our commands to run cobolcheck
          echo "Running COBOL Check"
          # Add actual cobolcheck commands here
      - name: Run Zowe operations
        env:
          ZOWE_OPT_HOST: 204.90.115.200
          ZOWE_OPT_PORT: 10443
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_OPT_REJECT_UNAUTHORIZED: false
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        run: |
            echo "run zowe operations"
            chmod +x .github/scripts/zowe_operations.sh
            .github/scripts/zowe_operations.sh

      - name: mainframe operations
        env:
          ZOWE_OPT_HOST: 204.90.115.200
          ZOWE_OPT_PORT: 10443
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_OPT_REJECT_UNAUTHORIZED: false
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        run: |
          run: |
          echo "run mainframe operations"
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
       #   sshpass -p "$ZOWE_PASSWORD" ssh -o StrictHostKeyChecking=no $ZOWE_USERNAME@204.90.115.200 'sh -s' < .github/scripts/mainframe_operations.sh
                 
   #   - name: zowe operations
   #     env:
   #        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
   #        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
   #     run: |
   #        echo "run zowe operations"
   #        chmod +x .github/scripts/zowe_operations.sh
   #        .github/scripts/zowe_operations.sh           
   #   - name: mainframe operations
   #     env:
   #       ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
   #       ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
   #     run: |
   #       echo "run mainframe operations"
   #       chmod +x .github/scripts/mainframe_operations.sh
   #       .github/scripts/mainframe_operations.sh

           
