name: COBOL Check Automation
on:
  push:
    branches: [main]
jobs:
    cobol-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Running cobol check 
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: 
          # Here we'll add our commands to run cobolcheck
          echo "Running COBOL Check"
          # Add actual cobolcheck commands here
      - name: zowe operations
        env:
           ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
           ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: 
           chmod +x .github/scripts/zowe_operations.sh
           .github/scripts/zowe_operations.sh
      - name: mainframe operations
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: 
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh

           
