name: COBOL Check Automation
on:
  push:
    branches: [main]
jobs:
    cobol-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
      - name: Setup Mainframe Environment and Upload 
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: 
          # Here we'll add our commands to run cobolcheck
          echo "Running COBOL Check"
          # Add actual cobolcheck commands here
